# Generated by Django 5.1.3 on 2024-12-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_pro_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.reg_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pro_tbl')),
            ],
        ),
    ]
